version: "3.8"
services:
  restapi:
    container_name: skyshi_gethired
    build:
      context: .
      dockerfile: ./docker/restapi.dockerfile
    restart: on-failure
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
    command: go run main.go -b 0.0.0.0
