version: "3.8"
services:
  restapi:
    container_name: skyshi_gethired
    build:
      context: .
      dockerfile: ./docker/restapi.dockerfile
    restart: on-failure
    ports:
      - "3030:3030"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DBNAME=skyshi_gethired
  mysql:
    container_name: skyshi_gethired_mysql
    image: mysql:latest
    ports:
      - "3036:3036"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
