version: "3.7"
services:
  restapi:
    container_name: skyshi_gethired
    build:
      context: .
      dockerfile: ./docker/restapi.dockerfile
    ports:
      - "3030:3030"
    volumes:
      - skyshi_gethired:/usr/src/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER="root"
      - DB_PASSWORD="root"
      - DB_DATABASE="skyshi_gethired"

  mysql:
    container_name: skyshi_gethired_mysql
    build:
      context: .
      dockerfile: ./docker/mysql.dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE=skyshi_gethired
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql:/docker-entrypoint-initdb.d

volumes:
  mysql:
  mysql_data:
  skyshi_gethired:
