version: "3.8"
services:
  restapi:
    container_name: skyshi-gethired
    build:
      context: .
      dockerfile: ./docker/restapi.dockerfile
    restart: on-failure
    ports:
      - "8090:3030"
    image: ezizull/skyshi-gethired:latest
    volumes:
      - .:/usr/src/app
    environment:
      - GOPATH=/usr/src/app
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
