version: "3.8"
services:
  restapi:
    container_name: skyshi_gethired
    build:
      context: .
      dockerfile: ./docker/restapi.dockerfile
    restart: on-failure
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DBNAME}
      # - GOPATH=/app
    command: go run main.go -b 0.0.0.0

  mysql:
    container_name: skyshi_gethired_mysql
    image: mysql:latest
    restart: always
    ports:
      - "8090:8090"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
    volumes:
      - mysql_db:/lib/mysql

volumes:
  mysql_db:
